export enum ROUTES {
  HOME = '/',
  NOT_FOUND = '/not-found',
  PLAYS = '/plays',
  PLAY_DETAILS = '/play-details',
  PLAYS_AND_HITS = '/plays-and-hits',
  TERMINAL_TICKET = '/terminal-ticket',
  RESULTS = '/results',
  CLIENTS = '/clients',
  AGENT_COMMISSION = '/agent-commission',
  SHIFTS = '/shifts',
  USERS = '/users',
  USERS_List = '/user-list',
  REPORTS = '/reports',
  SETTINGS = '/settings',
  LOGIN = '/login',
  LOTTERIES = '/upcoming-lotteries',
  CURRENT_ACCOUNT = '/current-account',
  GROUPS = '/groups',
  NEW_USER = '/new-user',
  RESET_PASSWORD = '/reset-password'
}
