export enum ROUTES {
  HOME = '/',
  NOT_FOUND = '/not-found',
  PLAYS = '/plays',
  MAKE_PLAYS = '/make-plays',
  PLAYS_AND_HITS = '/plays-and-hits',
  TERMINAL_TICKET = '/terminal-ticket',
  RESULTS = '/results',
  CLIENTS = '/clients',
  AGENT_COMMISSION = '/agent-commission',
  SHIFTS = '/shifts',
  USERS = '/users',
  USERS_LIST = '/user-list',
  REPORTS = '/reports',
  SETTINGS = '/settings',
  LOGIN = '/login',
  UPCOMING_LOTTERIES = '/upcoming-lotteries',
  LOTTERIES = '/lotteries',
  CURRENT_ACCOUNT = '/current-account',
  GROUPS = '/groups',
  NEW_USER = '/new-user',
  RESET_PASSWORD = '/reset-password',
  ORGANIZATIONS = '/organizations'
}
