export enum ROUTES {
  LOGIN = '/login',
  BETS = '/jugadas',
  MY_BETS = '/mis-jugadas',
  MAKE_BET = '/cargar-jugada',
  SALES = '/ventas',
  EDITIONS = '/ediciones',
  RESULTS = '/resultados',
  USERS = '/usuarios',
  CATALOGS = '/catalogos',
  ORGANIZATIONS = '/organizaciones',
  CURRENT_ACCOUNT = '/cuenta-corriente',
  CHANGE_PASSWORD = '/cambiar-password',
  SETTINGS = '/configuracion',
  NOT_FOUND = '/not-found',
}
