CREATE TABLE schedules (
  schedule_id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  time TIME NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  edited_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
