ALTER TABLE current_accounts
ADD COLUMN cashier_commission NUMERIC(12, 2) NOT NULL DEFAULT 0,
ADD COLUMN bills NUMERIC(12, 2) NOT NULL DEFAULT 0,
ADD COLUMN revenue NUMERIC(12, 2) NOT NULL DEFAULT 0,
ADD COLUMN previous_drag NUMERIC(12, 2) NOT NULL DEFAULT 0;
