/**
 * @deprecated Usar AppError classes en vez de ERROR_TYPE
 */
export declare enum ERROR_TYPE {
  NOT_FOUND = 0,
  USER_NOT_FOUND = 1,
  BAD_REQUEST = 2,
  INVALID_CREDENTIALS = 3,
  INTERNAL_SERVER_ERROR = 4,
  AUTH_ERROR = 5,
  USERNAME_IS_REQUIRED = 6,
  PASSWORD_IS_REQUIRED = 7,
  NAME_IS_REQUIRED = 8,
  CASHIER_NUMBER_IS_REQUIRED = 9,
  FORBIDDEN = 10,
  TOKEN_ERROR = 11,
  NEW_USER_REQUIRED = 12,
  ID_REQUIRED = 13,
  INVALID_ID = 14,
}
/**
 * @deprecated Usar AppError classes en vez de ERROR_MESSAGE
 */
export declare const ERROR_MESSAGE: {
  NOT_FOUND: string;
  USER_NOT_FOUND: string;
  BAD_REQUEST: string;
  INTERNAL_SERVER_ERROR: string;
  INVALID_CREDENTIALS: string;
  USERNAME_IS_REQUIRED: string;
  PASSWORD_IS_REQUIRED: string;
  NAME_IS_REQUIRED: string;
  CASHIER_NUMBER_IS_REQUIRED: string;
  FORBIDDEN: string;
  TOKEN_ERROR: string;
  AUTH_ERROR: string;
  NEW_USER_REQUIRED: string;
  ID_REQUIRED: string;
  INVALID_ID: string;
  INVALID_DELETE_TIME: string;
  TICKET_NOT_FOUND: string;
  TICKET_NOT_OWNED: string;
  TICKET_ALREADY_PAID: string;
  TICKET_NOT_WINNER: string;
  INVALID_USER_ID: string;
};
export declare const ERROR_CODES: {
  readonly BAD_REQUEST: 'BAD_REQUEST';
  readonly VALIDATION_ERROR: 'VALIDATION_ERROR';
  readonly INVALID_ID: 'INVALID_ID';
  readonly UNAUTHORIZED: 'UNAUTHORIZED';
  readonly INVALID_CREDENTIALS: 'INVALID_CREDENTIALS';
  readonly TOKEN_ERROR: 'TOKEN_ERROR';
  readonly FORBIDDEN: 'FORBIDDEN';
  readonly TICKET_NOT_OWNED: 'TICKET_NOT_OWNED';
  readonly NOT_FOUND: 'NOT_FOUND';
  readonly USER_NOT_FOUND: 'USER_NOT_FOUND';
  readonly TICKET_NOT_FOUND: 'TICKET_NOT_FOUND';
  readonly LOTTERY_NOT_FOUND: 'LOTTERY_NOT_FOUND';
  readonly CONFLICT: 'CONFLICT';
  readonly TICKET_ALREADY_PAID: 'TICKET_ALREADY_PAID';
  readonly INVALID_DELETE_TIME: 'INVALID_DELETE_TIME';
  readonly TICKET_NOT_WINNER: 'TICKET_NOT_WINNER';
  readonly INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR';
  readonly DATABASE_ERROR: 'DATABASE_ERROR';
};
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
