/* eslint-disable no-unused-vars */
export var SCHEDULE_DAY;
(function (SCHEDULE_DAY) {
    SCHEDULE_DAY[SCHEDULE_DAY["SUNDAY"] = 0] = "SUNDAY";
    SCHEDULE_DAY[SCHEDULE_DAY["MONDAY"] = 1] = "MONDAY";
    SCHEDULE_DAY[SCHEDULE_DAY["TUESDAY"] = 2] = "TUESDAY";
    SCHEDULE_DAY[SCHEDULE_DAY["WEDNESDAY"] = 3] = "WEDNESDAY";
    SCHEDULE_DAY[SCHEDULE_DAY["THURSDAY"] = 4] = "THURSDAY";
    SCHEDULE_DAY[SCHEDULE_DAY["FRIDAY"] = 5] = "FRIDAY";
    SCHEDULE_DAY[SCHEDULE_DAY["SATURDAY"] = 6] = "SATURDAY";
})(SCHEDULE_DAY || (SCHEDULE_DAY = {}));
